"""fts5 search index (SQLite only)

SQLite-specific DDL that SQLAlchemy's ORM has no vocabulary for, so it is hand-written
rather than autogenerated. See docs/ARCHITECTURE.md §4.5 for why external-content FTS5
with porter stemming, and why triggers rather than application-level sync.

This migration is a no-op on any other dialect — the Postgres equivalent (tsvector +
GIN index + trigger) lives in migration fe4d3f256097 so the same migration chain runs
unmodified against both the local SQLite dev database and the deployed Postgres
instance (docs/ARCHITECTURE.md ADR-006).

Revision ID: 52ec82d9f148
Revises: c9dd6ffef7eb
Create Date: 2026-09-07 15:41:56.716997
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "52ec82d9f148"
down_revision: str | None = "c9dd6ffef7eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if op.get_bind().dialect.name != "sqlite":
        return
    op.execute(
        """
        CREATE VIRTUAL TABLE segments_fts USING fts5(
          text,
          content='transcript_segments',
          content_rowid='id',
          tokenize='porter unicode61'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER segments_ai AFTER INSERT ON transcript_segments BEGIN
          INSERT INTO segments_fts(rowid, text) VALUES (new.id, new.text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER segments_ad AFTER DELETE ON transcript_segments BEGIN
          INSERT INTO segments_fts(segments_fts, rowid, text) VALUES('delete', old.id, old.text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER segments_au AFTER UPDATE ON transcript_segments BEGIN
          INSERT INTO segments_fts(segments_fts, rowid, text) VALUES('delete', old.id, old.text);
          INSERT INTO segments_fts(rowid, text) VALUES (new.id, new.text);
        END
        """
    )
    # Backfill in case this migration ever runs against a table that already has rows.
    op.execute("INSERT INTO segments_fts(rowid, text) SELECT id, text FROM transcript_segments")


def downgrade() -> None:
    if op.get_bind().dialect.name != "sqlite":
        return
    op.execute("DROP TRIGGER IF EXISTS segments_au")
    op.execute("DROP TRIGGER IF EXISTS segments_ad")
    op.execute("DROP TRIGGER IF EXISTS segments_ai")
    op.execute("DROP TABLE IF EXISTS segments_fts")
